version: '3'
services:
  mysql:
    image: mysql:latest
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_SCHEMA}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: your_root_password
    ports:
      - "8080:80"

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: your_access_key
      MINIO_SECRET_KEY: your_secret_key
    command: server /data
    volumes:
      - minio_data:/data

#  next-app:
#    image: next-app-dev
#    container_name: next-app-dev
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "3000:3000" # Exposing Next.js app on port 3000
#    depends_on:
#      - mysql
#      - redis
#      - minio
#    env_file:
#      - .env.docker
#    environment:
#      DB_HOST: ${DB_HOST}
#      DB_USER: ${DB_USER}
#      DB_PASS: ${DB_PASS}
#      DB_NAME: ${DB_SCHEMA}
#      NODE_ENV: ${NODE_ENV}
#    volumes:
#      - ./public/uploads:/app/public/uploads # Only persist the uploads folder
#    command: "npm run dev"

volumes:
  minio_data:
  mysql_data:
  redis_data:
